apiVersion: v1
kind: Service

metadata:
  name: ai-study-buddy-service
  namespace: ai-study-buddy

spec:
  type: NodePort

  selector:
    app: ai-study-buddy

  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001